# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-connx'
    subscriptionId: 'aac2dace-173c-4031-b808-fa227d94ae80'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'UAE North'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/femi-oz/mslearn-tailspin-spacegame-web-deploy/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName Space Game Web - Release'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'